<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFE4LBrR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFE4LBrR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFE4LBrR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFE4LBrR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFE4LBrR\App_KernelDevDebugContainer([
    'container.build_hash' => 'FE4LBrR',
    'container.build_id' => '41d51b8f',
    'container.build_time' => 1728926787,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFE4LBrR');
