<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUaljTSm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUaljTSm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUaljTSm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUaljTSm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUaljTSm\App_KernelDevDebugContainer([
    'container.build_hash' => 'UaljTSm',
    'container.build_id' => '9e544804',
    'container.build_time' => 1728153425,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUaljTSm');
