<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT0st4b8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT0st4b8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT0st4b8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT0st4b8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT0st4b8\App_KernelDevDebugContainer([
    'container.build_hash' => 'T0st4b8',
    'container.build_id' => '62be8f15',
    'container.build_time' => 1731443871,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT0st4b8');
