<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0t6mque\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0t6mque/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0t6mque.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0t6mque\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0t6mque\App_KernelDevDebugContainer([
    'container.build_hash' => '0t6mque',
    'container.build_id' => '1c1b7418',
    'container.build_time' => 1732128822,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0t6mque');
