<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcrD3uL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcrD3uL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcrD3uL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcrD3uL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAcrD3uL\App_KernelDevDebugContainer([
    'container.build_hash' => 'AcrD3uL',
    'container.build_id' => 'b103523e',
    'container.build_time' => 1731879192,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcrD3uL');
